In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [107]:
data=pd.read_csv('zomato.csv',encoding='latin-1')

In [108]:
data.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [109]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
Restaurant ID           9551 non-null int64
Restaurant Name         9551 non-null object
Country Code            9551 non-null int64
City                    9551 non-null object
Address                 9551 non-null object
Locality                9551 non-null object
Locality Verbose        9551 non-null object
Longitude               9551 non-null float64
Latitude                9551 non-null float64
Cuisines                9542 non-null object
Average Cost for two    9551 non-null int64
Currency                9551 non-null object
Has Table booking       9551 non-null object
Has Online delivery     9551 non-null object
Is delivering now       9551 non-null object
Switch to order menu    9551 non-null object
Price range             9551 non-null int64
Aggregate rating        9551 non-null float64
Rating color            9551 non-null object
Rating text             9551 non-null object
Votes                   9551 non-null int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [110]:
data.dropna(inplace=True)

In [111]:
data['Restaurant Name'].value_counts()

Cafe Coffee Day                  83
Domino's Pizza                   79
Subway                           63
Green Chick Chop                 51
McDonald's                       48
Keventers                        34
Pizza Hut                        30
Giani                            29
Baskin Robbins                   28
Barbeque Nation                  26
Barista                          22
Dunkin' Donuts                   22
Giani's                          22
Pind Balluchi                    20
Costa Coffee                     20
Wah Ji Wah                       19
Twenty Four Seven                19
Pizza Hut Delivery               19
Sagar Ratna                      19
Republic of Chicken              18
KFC                              18
Chaayos                          18
Starbucks                        18
Haldiram's                       16
Burger King                      16
Shree Rathnam                    15
Aggarwal Sweets                  14
Bikanervala                      14
Frontier                         14
Moti Mahal Delux                 14
                                 ..
Chawla Bakers                     1
New Durga Corner                  1
Bubba Jax Crab Shack              1
21 Gun Salute                     1
Cream Bell                        1
Austins Cattle Co                 1
Hello Sichuan                     1
Deep Chicken Point                1
Fresh Fast Food                   1
Best Biryani                      1
The Cafe Baraco                   1
Hari Om Bhojanalaya               1
Chocomore                         1
Outer Limits Fun Zone             1
LPK Waterfront                    1
Tandooriwala                      1
World In A Box                    1
Grover's - The Baker Shop         1
Meritage                          1
World Art Dining - Brew House     1
Nirmal Vada Pav                   1
The Street- Curries & Grills      1
Carnatic Cafe                     1
Pooja Take Away Kitchen           1
Shah Bakery                       1
Telegram                          1
Olive Tree Cafe                   1
Milko's                           1
CG's - Lounge Cafe Bar            1
A Vaishno Bhojnalaya              1
Name: Restaurant Name, Length: 7437, dtype: int64

In [112]:
data.drop(columns=['Restaurant ID','Restaurant ID','Switch to order menu'],inplace=True)

In [113]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes'],
      dtype='object')

In [114]:
data['Country Code'].nunique()

15

In [115]:
data['Country Code'].value_counts()

1      8652
216     425
215      80
214      60
30       60
189      60
148      40
208      34
14       24
162      22
94       21
191      20
166      20
184      20
37        4
Name: Country Code, dtype: int64

In [116]:
data=data[data['Country Code']==1]
data.shape

(8652, 19)

In [117]:
data.drop(columns=['Restaurant Name','Country Code','Currency'],inplace=True)

In [118]:
data.columns

Index(['City', 'Address', 'Locality', 'Locality Verbose', 'Longitude',
       'Latitude', 'Cuisines', 'Average Cost for two', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes'],
      dtype='object')

In [119]:
data['City'].nunique()

43

In [120]:
data=data[data['City'].isin(['New Delhi','Gurgaon','Noida','Faridabad'])]
data.shape

(7922, 16)

In [121]:
data.columns

Index(['City', 'Address', 'Locality', 'Locality Verbose', 'Longitude',
       'Latitude', 'Cuisines', 'Average Cost for two', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes'],
      dtype='object')

In [122]:
data['Locality'].value_counts()

Connaught Place                                 122
Rajouri Garden                                   99
Shahdara                                         87
Defence Colony                                   86
Pitampura                                        85
Malviya Nagar                                    84
Mayur Vihar Phase 1                              84
Rajinder Nagar                                   81
Safdarjung                                       80
Satyaniketan                                     79
Karol Bagh                                       76
Krishna Nagar                                    76
Sector 62                                        76
Sector 18                                        75
Hauz Khas                                        74
Kalkaji                                          73
Sector 15                                        71
Mahipalpur                                       69
DLF Phase 3                                      69
Mukherjee Nagar                                  68
Chandni Chowk                                    67
Shalimar Bagh                                    67
Greater Kailash (GK) 2                           66
Greater Kailash (GK) 1                           66
Delhi University-GTB Nagar                       65
Kamla Nagar                                      65
Paharganj                                        64
Vasundhara Enclave                               62
Jail Road                                        61
Sector 72                                        61
                                               ...
Lemon Tree Premier, Aerocity                      1
West Gate Mall, Rajouri Garden                    1
Trilokpuri                                        1
Park Inn, Sector 15, Gurgaon                      1
Aaya Nagar                                        1
Radisson Blu, Sector 18, Noida                    1
Indraprastha Colony                               1
SRS Mall, Sector 12, Faridabad                    1
Badkal Lake                                       1
Park Plaza, Sector 21, Faridabad                  1
Country Inn & Suites, Sohna Road                  1
JW Marriott New Delhi                             1
Piccadily Hotel, Janakpuri                        1
The Claremont, MG Road                            1
Country Inn & Suites By Carlson, Udyog Vihar      1
The Galgotias, Sector 23                          1
Park Ascent, Sector 62, Noida                     1
The Oberoi, Udyog Vihar                           1
Dayal Bagh                                        1
Worldmark 3, Aerocity                             1
Plaza Mall, MG Road                               1
Tughlakabad Institutional Area                    1
ARSS Mall, Paschim Vihar                          1
Race Course                                       1
Lemon Tree Premier, Sector 29                     1
Sector 6                                          1
Holiday Inn, Aerocity                             1
Mansingh Road                                     1
Cyber Greens, DLF Cyber City                      1
Dr. Zakir Hussain Marg                            1
Name: Locality, Length: 457, dtype: int64

In [123]:
avg_price=data.groupby('Cuisines').mean()['Average Cost for two'].reset_index()

In [124]:
data=data.merge(avg_price,on='Cuisines')

In [125]:
data

,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two_x,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Rating color,Rating text,Votes,Average Cost for two_y
0,Faridabad,"G 25/22, Main Road, 40 Feet, Molarband Extensi...",Badarpur Border,"Badarpur Border, Faridabad",77.306640,28.490059,"Chinese, Fast Food, Bakery",250,No,No,No,1,2.9,Orange,Average,4,375.000000
1,New Delhi,"Shop 3, Plot 1161, Opposite Old Sabji Mandi, K...",Narela,"Narela, New Delhi",77.049525,28.806199,"Chinese, Fast Food, Bakery",500,No,No,No,2,0.0,White,Not rated,0,375.000000
2,Faridabad,"11/6, Delhi Mathura Road, Near Bharat Petrol P...",Badarpur Border,"Badarpur Border, Faridabad",77.304776,28.490157,"North Indian, Chinese",500,No,No,No,2,2.8,Orange,Average,16,594.303797
3,Faridabad,"158/7, Opposite DDA Flat, Pul Pehlad Pur, Char...",Charmwood Village,"Charmwood Village, Faridabad",0.000000,0.000000,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,0,594.303797
4,Faridabad,"Hotel Saffron Kiran, 12/6, Adjacent to Badarpu...","Hotel Saffron Kiran, Faridabad","Hotel Saffron Kiran, Faridabad, Faridabad",77.305698,28.471985,"North Indian, Chinese",1200,Yes,No,No,3,0.0,White,Not rated,0,594.303797
5,Faridabad,"3G/1, NIT, Faridabad",NIT,"NIT, Faridabad",77.292278,28.398268,"North Indian, Chinese",400,No,No,No,1,0.0,White,Not rated,0,594.303797
6,Faridabad,"J-121, Near Lean Wolf Gym, Sector 10, Faridabad",Sector 10,"Sector 10, Faridabad",77.329161,28.375486,"North Indian, Chinese",450,No,No,No,1,2.8,Orange,Average,20,594.303797
7,Faridabad,"J140, Sector 10, Faridabad",Sector 10,"Sector 10, Faridabad",77.328898,28.377754,"North Indian, Chinese",700,Yes,No,No,2,2.9,Orange,Average,13,594.303797
8,Faridabad,"18, DLF Market, Sector 11, Faridabad",Sector 11,"Sector 11, Faridabad",77.318483,28.371951,"North Indian, Chinese",450,No,No,No,1,2.6,Orange,Average,26,594.303797
9,Faridabad,"11-12 Dividing Road, Sector 12, Faridabad",Sector 12,"Sector 12, Faridabad",77.314446,28.381192,"North Indian, Chinese",550,No,No,No,2,0.0,White,Not rated,0,594.303797
10,Faridabad,"Plot 6, Bata Chowk, BIryaniwali Gali, Sector 1...",Sector 12,"Sector 12, Faridabad",0.000000,0.000000,"North Indian, Chinese",400,No,No,No,1,0.0,White,Not rated,0,594.303797
11,Faridabad,"SCF 58, Ground Floor, Sector 15, Faridabad",Sector 15,"Sector 15, Faridabad",77.322930,28.395009,"North Indian, Chinese",600,No,Yes,No,2,3.2,Orange,Average,31,594.303797
12,Faridabad,"Shop 139, Main HUDA Market, Sector 16, Faridabad",Sector 16,"Sector 16, Faridabad",77.318577,28.410708,"North Indian, Chinese",400,No,No,No,1,0.0,White,Not rated,0,594.303797
13,Faridabad,"31, Near HDFC Bank ATM, Sector 17 Market, Sect...",Sector 17,"Sector 17, Faridabad",77.328898,28.410603,"North Indian, Chinese",600,No,Yes,No,2,2.7,Orange,Average,56,594.303797
14,Faridabad,"Shop 32, HUDA Market, Sector 19, Faridabad",Sector 19,"Sector 19, Faridabad",77.313820,28.417529,"North Indian, Chinese",200,No,No,No,1,3.0,Orange,Average,6,594.303797
15,Faridabad,"Ground Floor, 45 SLF Mall, IP Colony, Sector-3...",Sector 31,"Sector 31, Faridabad",77.315951,28.454997,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,1,594.303797
16,Faridabad,"SCF 146/37, HUDA Complex, Delhi Badarpur Borde...",Sector 37,"Sector 37, Faridabad",77.310500,28.480467,"North Indian, Chinese",1000,Yes,No,No,3,2.7,Orange,Average,70,594.303797
17,Faridabad,"Shop 44, Huda Market, Sector 37, Faridabad",Sector 37,"Sector 37, Faridabad",77.311397,28.480552,"North Indian, Chinese",300,No,No,No,1,2.9,Orange,Average,14,594.303797
18,Faridabad,"Shop 65, HUDA Market, Sector 37, Faridabad",Sector 37,"Sector 37, Faridabad",77.311487,28.480829,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,0,594.303797
19,Faridabad,"Shop 15, Main Road, Sector 37, Faridabad",Sector 37,"Sector 37, Faridabad",77.305606,28.480730,"North Indian, Chinese",500,No,No,No,2,0.0,White,Not rated,0,594.303797
20,Faridabad,"B-263, Green Field Colony, Sector 42, Faridabad",Sector 42,"Sector 42, Faridabad",0.000000,0.000000,"North Indian, Chinese",600,No,No,No,2,0.0,White,Not rated,0,594.303797
21,Faridabad,"B-1212, Ground Floor, Front Side, Green Fields...",Sector 42,"Sector 42, Faridabad",0.000000,0.000000,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,0,594.303797
22,Faridabad,"Shop 140, Main Market, Sector 7, Faridabad",Sector 7,"Sector 7, Faridabad",77.325997,28.363899,"North Indian, Chinese",250,No,No,No,1,3.0,Orange,Average,7,594.303797
23,Faridabad,"Shop 2385, Sector 7A, Near Sector 7, Faridabad",Sector 7,"Sector 7, Faridabad",77.328539,28.368654,"North Indian, Chinese",500,No,No,No,2,3.0,Orange,Average,4,594.303797
24,Faridabad,"Shop 72, Near Omaxe Heights, Gate 2, Sector 86...",Sector 86,"Sector 86, Faridabad",77.336451,28.408678,"North Indian, Chinese",650,No,No,No,2,3.2,Orange,Average,24,594.303797
25,Faridabad,"SRS Royal Hills, Near Club Sec 87, Sector 86, ...",Sector 86,"Sector 86, Faridabad",77.342313,28.412268,"North Indian, Chinese",500,No,No,No,2,2.9,Orange,Average,8,594.303797
26,Faridabad,"Tigaon Road, Near Omaxe, Sector 86, Faridabad",Sector 86,"Sector 86, Faridabad",77.336292,28.410219,"North Indian, Chinese",500,No,Yes,No,2,3.2,Orange,Average,39,594.303797
27,Faridabad,"H-250, B/10, 60 Feet Road, Pul Prahladpur, Sur...",Suraj Kund,"Suraj Kund, Faridabad",77.293759,28.498215,"North Indian, Chinese",500,No,No,No,2,2.8,Orange,Average,13,594.303797
28,Faridabad,"B-147, Naveen Plaza, Sharma Market, Prahladpur...",Suraj Kund,"Suraj Kund, Faridabad",77.293041,28.499223,"North Indian, Chinese",600,No,No,No,2,3.1,Orange,Average,18,594.303797
29,Gurgaon,"Ardee City, Gurgaon",Ardee City,"Ardee City, Gurgaon",77.078058,28.432548,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,2,594.303797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7892,Noida,"1st Floor, C Block Market, Sector 41, Noida",Sector 41,"Sector 41, Noida",77.361828,28.569250,"American, Italian, North Indian, Chinese",500,No,No,No,2,0.0,White,Not rated,3,500.000000
7893,Noida,"Glued Reloaded, Dynamic House, Opposite Petrol...",Sector 41,"Sector 41, Noida",77.360975,28.561503,"North Indian, Mughlai, Mughlai",600,No,No,No,2,0.0,White,Not rated,2,600.000000
7894,Noida,"Block C Road, Sector 41, Noida",Sector 41,"Sector 41, Noida",77.362094,28.569279,"Salad, Continental",500,No,Yes,No,2,4.1,Green,Very Good,43,500.000000
7895,Noida,"A15/11, 1st Floor, Sector 44, Noida",Sector 44,"Sector 44, Noida",0.000000,0.000000,"Continental, Chinese",500,No,No,No,2,3.0,Orange,Average,4,500.000000
7896,Noida,"F Block, Sector 50, Noida",Sector 50,"Sector 50, Noida",77.361977,28.570281,"North Indian, Healthy Food, Rajasthani",400,No,No,No,1,3.1,Orange,Average,10,400.000000
7897,Noida,"B-1/39 Central, Sector 50, Noida",Sector 50,"Sector 50, Noida",77.362309,28.570602,"Fast Food, Cafe, Italian, North Indian, Chinese",550,No,Yes,Yes,2,3.2,Orange,Average,48,550.000000
7898,Noida,"H 38, Sector 51, Noida",Sector 51,"Sector 51, Noida",77.369364,28.578298,"Healthy Food, North Indian, Chinese, Continental",600,No,Yes,No,2,3.7,Yellow,Good,142,600.000000
7899,Noida,"1, Near VDS Market, Hoshiyarpur, Sector 51, Noida",Sector 51,"Sector 51, Noida",0.000000,0.000000,"Awadhi, North Indian",300,No,No,No,1,0.0,White,Not rated,2,300.000000
7900,Noida,"Sector 51, Noida",Sector 51,"Sector 51, Noida",77.374547,28.581684,"Tibetan, Street Food",100,No,No,No,1,0.0,White,Not rated,1,100.000000
7901,Noida,"Sector 51, Noida",Sector 51,"Sector 51, Noida",0.000000,0.000000,"Mexican, Italian",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7902,Noida,"4th Floor, Hoshiarpur Market, Sector 51, Noida",Sector 51,"Sector 51, Noida",77.366121,28.581868,"Cafe, Mexican",550,No,Yes,No,2,0.0,White,Not rated,2,550.000000
7903,Noida,"K-1-4, Kanchanjunga Market, Sector 53, Noida",Sector 53,"Sector 53, Noida",77.362594,28.595375,"North Indian, Mughlai, Chinese, Raw Meats",600,No,No,No,2,2.9,Orange,Average,25,600.000000
7904,Noida,"Shop 6-A, B Block Market, Sector 53, Noida",Sector 53,"Sector 53, Noida",77.365506,28.591384,"Continental, Fast Food, Asian, Italian",500,No,Yes,No,2,3.8,Yellow,Good,200,500.000000
7905,Noida,"C-25, Near IT Park, Sector 62, Noida",Sector 62,"Sector 62, Noida",77.362456,28.612791,"North Indian, South Indian, Chinese, Street Fo...",500,No,No,No,2,2.4,Red,Poor,77,500.000000
7906,Noida,"Sector 63, Noida",Sector 63,"Sector 63, Noida",0.000000,0.000000,"North Indian, Chinese, Italian, Thai",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7907,Noida,"Shop 3 & 4, Amrapali Princely Estate , Sector ...",Sector 72,"Sector 72, Noida",77.382379,28.564510,"Mithai, North Indian, Chinese",400,No,No,No,1,2.9,Orange,Average,4,400.000000
7908,Noida,"Shop 28, Amarpali Princely Estate, Sector 76, ...",Sector 72,"Sector 72, Noida",77.381327,28.566393,"Fast Food, Italian, Desserts, Beverages",350,No,No,No,1,3.3,Orange,Average,12,350.000000
7909,Noida,"Near Ajnara Clock Tower, Sector 77, Near Secto...",Sector 72,"Sector 72, Noida",77.392072,28.571730,"Kashmiri, Chinese",500,No,No,No,2,3.1,Orange,Average,6,500.000000
7910,Noida,"Shop 7, Singhal Residency, Arya Nagar, Sector ...",Sector 72,"Sector 72, Noida",77.380397,28.589199,"Bakery, North Indian",250,No,No,No,1,0.0,White,Not rated,0,250.000000
7911,Noida,"Sector 72, Noida",Sector 72,"Sector 72, Noida",77.400003,28.588073,"Italian, Continental, American",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7912,Noida,"Sector 122, Near, Sector 72, Noida",Sector 72,"Sector 72, Noida",77.334697,28.541939,"Lucknowi, Mughlai, North Indian",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7913,Noida,"Shop 4, Golf City, Street Mart, Sector 75, Sec...",Sector 72,"Sector 72, Noida",77.380418,28.571616,"North Indian, Chinese, Kashmiri",600,No,No,No,2,0.0,White,Not rated,3,600.000000
7914,Noida,"Eldeco Convenience Shopping Area, GF, Eldeco S...",Sector 93,"Sector 93, Noida",77.385331,28.514600,"Mithai, Beverages",200,No,No,No,1,3.4,Orange,Average,23,200.000000
7915,Noida,"311A, 2nd Floor, Spice World Mall, Sector 25, ...","Spice World Mall, Sector 25","Spice World Mall, Sector 25, Noida",77.341371,28.586239,"North Indian, Chinese, Mediterranean, Asian, C...",1300,No,No,No,3,3.9,Yellow,Good,1088,1300.000000
7916,Noida,"Shop K2 -K5, 2nd Floor, Spice World Mall, Sect...","Spice World Mall, Sector 25","Spice World Mall, Sector 25, Noida",77.337325,28.583579,"North Indian, South Indian, Bakery, Beverages",500,No,No,No,2,0.0,White,Not rated,2,500.000000
7917,Noida,"205-A, 1st Floor, Spice World Mall, Sector 25-...","Spice World Mall, Sector 25","Spice World Mall, Sector 25, Noida",77.341021,28.585493,"European, North Indian, Chinese",2500,Yes,No,No,4,2.2,Red,Poor,116,2500.000000
7918,Noida,"101, Food Court, Supertech Shopprix Mall, Sect...","Supertech Shopprix Mall, Sector 61","Supertech Shopprix Mall, Sector 61, Noida",77.364833,28.597103,"Juices, Beverages, Fast Food",200,No,No,No,1,3.0,Orange,Average,10,200.000000
7919,Noida,"63-C, 134-B, Supertech Shopprix Mall, Sector 6...","Supertech Shopprix Mall, Sector 61","Supertech Shopprix Mall, Sector 61, Noida",77.364833,28.597103,"Bakery, Desserts, Fast Food, North Indian",450,No,Yes,No,1,3.5,Yellow,Good,105,450.000000
7920,Noida,"320-A, 3rd Floor, The Great India Place Mall, ...","The Great India Place, Sector 38","The Great India Place, Sector 38, Noida",77.323213,28.567751,"Continental, Lebanese, Mexican",1000,Yes,No,No,3,0.0,White,Not rated,0,1000.000000
7921,Noida,"A-2, 3rd Floor, The Great India Place Mall, Se...","The Great India Place, Sector 38","The Great India Place, Sector 38, Noida",77.325308,28.567150,"Chinese, North Indian, South Indian, Fast Food",450,No,No,No,1,2.0,Red,Poor,161,450.000000

In [126]:
data

,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two_x,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Rating color,Rating text,Votes,Average Cost for two_y
0,Faridabad,"G 25/22, Main Road, 40 Feet, Molarband Extensi...",Badarpur Border,"Badarpur Border, Faridabad",77.306640,28.490059,"Chinese, Fast Food, Bakery",250,No,No,No,1,2.9,Orange,Average,4,375.000000
1,New Delhi,"Shop 3, Plot 1161, Opposite Old Sabji Mandi, K...",Narela,"Narela, New Delhi",77.049525,28.806199,"Chinese, Fast Food, Bakery",500,No,No,No,2,0.0,White,Not rated,0,375.000000
2,Faridabad,"11/6, Delhi Mathura Road, Near Bharat Petrol P...",Badarpur Border,"Badarpur Border, Faridabad",77.304776,28.490157,"North Indian, Chinese",500,No,No,No,2,2.8,Orange,Average,16,594.303797
3,Faridabad,"158/7, Opposite DDA Flat, Pul Pehlad Pur, Char...",Charmwood Village,"Charmwood Village, Faridabad",0.000000,0.000000,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,0,594.303797
4,Faridabad,"Hotel Saffron Kiran, 12/6, Adjacent to Badarpu...","Hotel Saffron Kiran, Faridabad","Hotel Saffron Kiran, Faridabad, Faridabad",77.305698,28.471985,"North Indian, Chinese",1200,Yes,No,No,3,0.0,White,Not rated,0,594.303797
5,Faridabad,"3G/1, NIT, Faridabad",NIT,"NIT, Faridabad",77.292278,28.398268,"North Indian, Chinese",400,No,No,No,1,0.0,White,Not rated,0,594.303797
6,Faridabad,"J-121, Near Lean Wolf Gym, Sector 10, Faridabad",Sector 10,"Sector 10, Faridabad",77.329161,28.375486,"North Indian, Chinese",450,No,No,No,1,2.8,Orange,Average,20,594.303797
7,Faridabad,"J140, Sector 10, Faridabad",Sector 10,"Sector 10, Faridabad",77.328898,28.377754,"North Indian, Chinese",700,Yes,No,No,2,2.9,Orange,Average,13,594.303797
8,Faridabad,"18, DLF Market, Sector 11, Faridabad",Sector 11,"Sector 11, Faridabad",77.318483,28.371951,"North Indian, Chinese",450,No,No,No,1,2.6,Orange,Average,26,594.303797
9,Faridabad,"11-12 Dividing Road, Sector 12, Faridabad",Sector 12,"Sector 12, Faridabad",77.314446,28.381192,"North Indian, Chinese",550,No,No,No,2,0.0,White,Not rated,0,594.303797
10,Faridabad,"Plot 6, Bata Chowk, BIryaniwali Gali, Sector 1...",Sector 12,"Sector 12, Faridabad",0.000000,0.000000,"North Indian, Chinese",400,No,No,No,1,0.0,White,Not rated,0,594.303797
11,Faridabad,"SCF 58, Ground Floor, Sector 15, Faridabad",Sector 15,"Sector 15, Faridabad",77.322930,28.395009,"North Indian, Chinese",600,No,Yes,No,2,3.2,Orange,Average,31,594.303797
12,Faridabad,"Shop 139, Main HUDA Market, Sector 16, Faridabad",Sector 16,"Sector 16, Faridabad",77.318577,28.410708,"North Indian, Chinese",400,No,No,No,1,0.0,White,Not rated,0,594.303797
13,Faridabad,"31, Near HDFC Bank ATM, Sector 17 Market, Sect...",Sector 17,"Sector 17, Faridabad",77.328898,28.410603,"North Indian, Chinese",600,No,Yes,No,2,2.7,Orange,Average,56,594.303797
14,Faridabad,"Shop 32, HUDA Market, Sector 19, Faridabad",Sector 19,"Sector 19, Faridabad",77.313820,28.417529,"North Indian, Chinese",200,No,No,No,1,3.0,Orange,Average,6,594.303797
15,Faridabad,"Ground Floor, 45 SLF Mall, IP Colony, Sector-3...",Sector 31,"Sector 31, Faridabad",77.315951,28.454997,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,1,594.303797
16,Faridabad,"SCF 146/37, HUDA Complex, Delhi Badarpur Borde...",Sector 37,"Sector 37, Faridabad",77.310500,28.480467,"North Indian, Chinese",1000,Yes,No,No,3,2.7,Orange,Average,70,594.303797
17,Faridabad,"Shop 44, Huda Market, Sector 37, Faridabad",Sector 37,"Sector 37, Faridabad",77.311397,28.480552,"North Indian, Chinese",300,No,No,No,1,2.9,Orange,Average,14,594.303797
18,Faridabad,"Shop 65, HUDA Market, Sector 37, Faridabad",Sector 37,"Sector 37, Faridabad",77.311487,28.480829,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,0,594.303797
19,Faridabad,"Shop 15, Main Road, Sector 37, Faridabad",Sector 37,"Sector 37, Faridabad",77.305606,28.480730,"North Indian, Chinese",500,No,No,No,2,0.0,White,Not rated,0,594.303797
20,Faridabad,"B-263, Green Field Colony, Sector 42, Faridabad",Sector 42,"Sector 42, Faridabad",0.000000,0.000000,"North Indian, Chinese",600,No,No,No,2,0.0,White,Not rated,0,594.303797
21,Faridabad,"B-1212, Ground Floor, Front Side, Green Fields...",Sector 42,"Sector 42, Faridabad",0.000000,0.000000,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,0,594.303797
22,Faridabad,"Shop 140, Main Market, Sector 7, Faridabad",Sector 7,"Sector 7, Faridabad",77.325997,28.363899,"North Indian, Chinese",250,No,No,No,1,3.0,Orange,Average,7,594.303797
23,Faridabad,"Shop 2385, Sector 7A, Near Sector 7, Faridabad",Sector 7,"Sector 7, Faridabad",77.328539,28.368654,"North Indian, Chinese",500,No,No,No,2,3.0,Orange,Average,4,594.303797
24,Faridabad,"Shop 72, Near Omaxe Heights, Gate 2, Sector 86...",Sector 86,"Sector 86, Faridabad",77.336451,28.408678,"North Indian, Chinese",650,No,No,No,2,3.2,Orange,Average,24,594.303797
25,Faridabad,"SRS Royal Hills, Near Club Sec 87, Sector 86, ...",Sector 86,"Sector 86, Faridabad",77.342313,28.412268,"North Indian, Chinese",500,No,No,No,2,2.9,Orange,Average,8,594.303797
26,Faridabad,"Tigaon Road, Near Omaxe, Sector 86, Faridabad",Sector 86,"Sector 86, Faridabad",77.336292,28.410219,"North Indian, Chinese",500,No,Yes,No,2,3.2,Orange,Average,39,594.303797
27,Faridabad,"H-250, B/10, 60 Feet Road, Pul Prahladpur, Sur...",Suraj Kund,"Suraj Kund, Faridabad",77.293759,28.498215,"North Indian, Chinese",500,No,No,No,2,2.8,Orange,Average,13,594.303797
28,Faridabad,"B-147, Naveen Plaza, Sharma Market, Prahladpur...",Suraj Kund,"Suraj Kund, Faridabad",77.293041,28.499223,"North Indian, Chinese",600,No,No,No,2,3.1,Orange,Average,18,594.303797
29,Gurgaon,"Ardee City, Gurgaon",Ardee City,"Ardee City, Gurgaon",77.078058,28.432548,"North Indian, Chinese",300,No,No,No,1,0.0,White,Not rated,2,594.303797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7892,Noida,"1st Floor, C Block Market, Sector 41, Noida",Sector 41,"Sector 41, Noida",77.361828,28.569250,"American, Italian, North Indian, Chinese",500,No,No,No,2,0.0,White,Not rated,3,500.000000
7893,Noida,"Glued Reloaded, Dynamic House, Opposite Petrol...",Sector 41,"Sector 41, Noida",77.360975,28.561503,"North Indian, Mughlai, Mughlai",600,No,No,No,2,0.0,White,Not rated,2,600.000000
7894,Noida,"Block C Road, Sector 41, Noida",Sector 41,"Sector 41, Noida",77.362094,28.569279,"Salad, Continental",500,No,Yes,No,2,4.1,Green,Very Good,43,500.000000
7895,Noida,"A15/11, 1st Floor, Sector 44, Noida",Sector 44,"Sector 44, Noida",0.000000,0.000000,"Continental, Chinese",500,No,No,No,2,3.0,Orange,Average,4,500.000000
7896,Noida,"F Block, Sector 50, Noida",Sector 50,"Sector 50, Noida",77.361977,28.570281,"North Indian, Healthy Food, Rajasthani",400,No,No,No,1,3.1,Orange,Average,10,400.000000
7897,Noida,"B-1/39 Central, Sector 50, Noida",Sector 50,"Sector 50, Noida",77.362309,28.570602,"Fast Food, Cafe, Italian, North Indian, Chinese",550,No,Yes,Yes,2,3.2,Orange,Average,48,550.000000
7898,Noida,"H 38, Sector 51, Noida",Sector 51,"Sector 51, Noida",77.369364,28.578298,"Healthy Food, North Indian, Chinese, Continental",600,No,Yes,No,2,3.7,Yellow,Good,142,600.000000
7899,Noida,"1, Near VDS Market, Hoshiyarpur, Sector 51, Noida",Sector 51,"Sector 51, Noida",0.000000,0.000000,"Awadhi, North Indian",300,No,No,No,1,0.0,White,Not rated,2,300.000000
7900,Noida,"Sector 51, Noida",Sector 51,"Sector 51, Noida",77.374547,28.581684,"Tibetan, Street Food",100,No,No,No,1,0.0,White,Not rated,1,100.000000
7901,Noida,"Sector 51, Noida",Sector 51,"Sector 51, Noida",0.000000,0.000000,"Mexican, Italian",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7902,Noida,"4th Floor, Hoshiarpur Market, Sector 51, Noida",Sector 51,"Sector 51, Noida",77.366121,28.581868,"Cafe, Mexican",550,No,Yes,No,2,0.0,White,Not rated,2,550.000000
7903,Noida,"K-1-4, Kanchanjunga Market, Sector 53, Noida",Sector 53,"Sector 53, Noida",77.362594,28.595375,"North Indian, Mughlai, Chinese, Raw Meats",600,No,No,No,2,2.9,Orange,Average,25,600.000000
7904,Noida,"Shop 6-A, B Block Market, Sector 53, Noida",Sector 53,"Sector 53, Noida",77.365506,28.591384,"Continental, Fast Food, Asian, Italian",500,No,Yes,No,2,3.8,Yellow,Good,200,500.000000
7905,Noida,"C-25, Near IT Park, Sector 62, Noida",Sector 62,"Sector 62, Noida",77.362456,28.612791,"North Indian, South Indian, Chinese, Street Fo...",500,No,No,No,2,2.4,Red,Poor,77,500.000000
7906,Noida,"Sector 63, Noida",Sector 63,"Sector 63, Noida",0.000000,0.000000,"North Indian, Chinese, Italian, Thai",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7907,Noida,"Shop 3 & 4, Amrapali Princely Estate , Sector ...",Sector 72,"Sector 72, Noida",77.382379,28.564510,"Mithai, North Indian, Chinese",400,No,No,No,1,2.9,Orange,Average,4,400.000000
7908,Noida,"Shop 28, Amarpali Princely Estate, Sector 76, ...",Sector 72,"Sector 72, Noida",77.381327,28.566393,"Fast Food, Italian, Desserts, Beverages",350,No,No,No,1,3.3,Orange,Average,12,350.000000
7909,Noida,"Near Ajnara Clock Tower, Sector 77, Near Secto...",Sector 72,"Sector 72, Noida",77.392072,28.571730,"Kashmiri, Chinese",500,No,No,No,2,3.1,Orange,Average,6,500.000000
7910,Noida,"Shop 7, Singhal Residency, Arya Nagar, Sector ...",Sector 72,"Sector 72, Noida",77.380397,28.589199,"Bakery, North Indian",250,No,No,No,1,0.0,White,Not rated,0,250.000000
7911,Noida,"Sector 72, Noida",Sector 72,"Sector 72, Noida",77.400003,28.588073,"Italian, Continental, American",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7912,Noida,"Sector 122, Near, Sector 72, Noida",Sector 72,"Sector 72, Noida",77.334697,28.541939,"Lucknowi, Mughlai, North Indian",500,No,No,No,2,0.0,White,Not rated,0,500.000000
7913,Noida,"Shop 4, Golf City, Street Mart, Sector 75, Sec...",Sector 72,"Sector 72, Noida",77.380418,28.571616,"North Indian, Chinese, Kashmiri",600,No,No,No,2,0.0,White,Not rated,3,600.000000
7914,Noida,"Eldeco Convenience Shopping Area, GF, Eldeco S...",Sector 93,"Sector 93, Noida",77.385331,28.514600,"Mithai, Beverages",200,No,No,No,1,3.4,Orange,Average,23,200.000000
7915,Noida,"311A, 2nd Floor, Spice World Mall, Sector 25, ...","Spice World Mall, Sector 25","Spice World Mall, Sector 25, Noida",77.341371,28.586239,"North Indian, Chinese, Mediterranean, Asian, C...",1300,No,No,No,3,3.9,Yellow,Good,1088,1300.000000
7916,Noida,"Shop K2 -K5, 2nd Floor, Spice World Mall, Sect...","Spice World Mall, Sector 25","Spice World Mall, Sector 25, Noida",77.337325,28.583579,"North Indian, South Indian, Bakery, Beverages",500,No,No,No,2,0.0,White,Not rated,2,500.000000
7917,Noida,"205-A, 1st Floor, Spice World Mall, Sector 25-...","Spice World Mall, Sector 25","Spice World Mall, Sector 25, Noida",77.341021,28.585493,"European, North Indian, Chinese",2500,Yes,No,No,4,2.2,Red,Poor,116,2500.000000
7918,Noida,"101, Food Court, Supertech Shopprix Mall, Sect...","Supertech Shopprix Mall, Sector 61","Supertech Shopprix Mall, Sector 61, Noida",77.364833,28.597103,"Juices, Beverages, Fast Food",200,No,No,No,1,3.0,Orange,Average,10,200.000000
7919,Noida,"63-C, 134-B, Supertech Shopprix Mall, Sector 6...","Supertech Shopprix Mall, Sector 61","Supertech Shopprix Mall, Sector 61, Noida",77.364833,28.597103,"Bakery, Desserts, Fast Food, North Indian",450,No,Yes,No,1,3.5,Yellow,Good,105,450.000000
7920,Noida,"320-A, 3rd Floor, The Great India Place Mall, ...","The Great India Place, Sector 38","The Great India Place, Sector 38, Noida",77.323213,28.567751,"Continental, Lebanese, Mexican",1000,Yes,No,No,3,0.0,White,Not rated,0,1000.000000
7921,Noida,"A-2, 3rd Floor, The Great India Place Mall, Se...","The Great India Place, Sector 38","The Great India Place, Sector 38, Noida",77.325308,28.567150,"Chinese, North Indian, South Indian, Fast Food",450,No,No,No,1,2.0,Red,Poor,161,450.000000

In [127]:
data.rename(columns={'Average Cost for two_y':'Cuisine','Average Cost for two_x':'target'},inplace=True)

In [128]:
data.columns

Index(['City', 'Address', 'Locality', 'Locality Verbose', 'Longitude',
       'Latitude', 'Cuisines', 'target', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes', 'Cuisine'],
      dtype='object')

In [129]:
data.drop(columns=['Locality Verbose','Locality','Address','Cuisines'],inplace=True)

In [130]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'target', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes', 'Cuisine'],
      dtype='object')

In [131]:
data['Has Online delivery'].value_counts()

No     5609
Yes    2313
Name: Has Online delivery, dtype: int64

In [132]:
data['Has Table booking'].replace("No",0,inplace=True)
data['Has Table booking'].replace("Yes",1,inplace=True)

In [133]:
data['Has Table booking'].value_counts()

0    6876
1    1046
Name: Has Table booking, dtype: int64

In [134]:
data['Has Online delivery'].replace("No",0,inplace=True)
data['Has Online delivery'].replace("Yes",1,inplace=True)

In [135]:
data['Has Online delivery'].value_counts()

0    5609
1    2313
Name: Has Online delivery, dtype: int64

In [136]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'target', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes', 'Cuisine'],
      dtype='object')

In [137]:
data['Price range'].value_counts()

1    4221
2    2583
3     814
4     304
Name: Price range, dtype: int64

In [138]:
data['Rating color'].value_counts()

Orange        3571
White         2137
Yellow        1580
Green          413
Red            178
Dark Green      43
Name: Rating color, dtype: int64

In [139]:
data.corr()

,Longitude,Latitude,target,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,Cuisine
Longitude,1.000000,0.997829,0.071752,0.059417,0.138671,0.083845,0.224523,0.071641,0.048805
Latitude,0.997829,1.000000,0.070993,0.059974,0.138488,0.083131,0.224383,0.071598,0.048014
target,0.071752,0.070993,1.000000,0.642966,0.076953,0.847985,0.328440,0.299089,0.808274
Has Table booking,0.059417,0.059974,0.642966,1.000000,0.074300,0.658627,0.248363,0.223811,0.563860
Has Online delivery,0.138671,0.138488,0.076953,0.074300,1.000000,0.188798,0.341197,0.123734,0.063178
Price range,0.083845,0.083131,0.847985,0.658627,0.188798,1.000000,0.370212,0.325602,0.720934
Aggregate rating,0.224523,0.224383,0.328440,0.248363,0.341197,0.370212,1.000000,0.291076,0.267418
Votes,0.071641,0.071598,0.299089,0.223811,0.123734,0.325602,0.291076,1.000000,0.274963
Cuisine,0.048805,0.048014,0.808274,0.563860,0.063178,0.720934,0.267418,0.274963,1.000000

In [143]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'target', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes', 'Cuisine'],
      dtype='object')

In [144]:
data.corr()

,Longitude,Latitude,target,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,Cuisine
Longitude,1.000000,0.997829,0.071752,0.059417,0.138671,0.083845,0.224523,0.071641,0.048805
Latitude,0.997829,1.000000,0.070993,0.059974,0.138488,0.083131,0.224383,0.071598,0.048014
target,0.071752,0.070993,1.000000,0.642966,0.076953,0.847985,0.328440,0.299089,0.808274
Has Table booking,0.059417,0.059974,0.642966,1.000000,0.074300,0.658627,0.248363,0.223811,0.563860
Has Online delivery,0.138671,0.138488,0.076953,0.074300,1.000000,0.188798,0.341197,0.123734,0.063178
Price range,0.083845,0.083131,0.847985,0.658627,0.188798,1.000000,0.370212,0.325602,0.720934
Aggregate rating,0.224523,0.224383,0.328440,0.248363,0.341197,0.370212,1.000000,0.291076,0.267418
Votes,0.071641,0.071598,0.299089,0.223811,0.123734,0.325602,0.291076,1.000000,0.274963
Cuisine,0.048805,0.048014,0.808274,0.563860,0.063178,0.720934,0.267418,0.274963,1.000000

In [145]:
data.corr()['target']

Longitude              0.071752
Latitude               0.070993
target                 1.000000
Has Table booking      0.642966
Has Online delivery    0.076953
Price range            0.847985
Aggregate rating       0.328440
Votes                  0.299089
Cuisine                0.808274
Name: target, dtype: float64

In [146]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'target', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes', 'Cuisine'],
      dtype='object')

In [148]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'target', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes', 'Cuisine'],
      dtype='object')

In [160]:
data['Price range'].value_counts()

1    4221
2    2583
3     814
4     304
Name: Price range, dtype: int64

In [162]:
data['Rating color'].value_counts()

Orange        3571
White         2137
Yellow        1580
Green          413
Red            178
Dark Green      43
Name: Rating color, dtype: int64

In [163]:
data.corr()

,Longitude,Latitude,target,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,Cuisine
Longitude,1.000000,0.997829,0.071752,0.059417,0.138671,0.083845,0.224523,0.071641,0.048805
Latitude,0.997829,1.000000,0.070993,0.059974,0.138488,0.083131,0.224383,0.071598,0.048014
target,0.071752,0.070993,1.000000,0.642966,0.076953,0.847985,0.328440,0.299089,0.808274
Has Table booking,0.059417,0.059974,0.642966,1.000000,0.074300,0.658627,0.248363,0.223811,0.563860
Has Online delivery,0.138671,0.138488,0.076953,0.074300,1.000000,0.188798,0.341197,0.123734,0.063178
Price range,0.083845,0.083131,0.847985,0.658627,0.188798,1.000000,0.370212,0.325602,0.720934
Aggregate rating,0.224523,0.224383,0.328440,0.248363,0.341197,0.370212,1.000000,0.291076,0.267418
Votes,0.071641,0.071598,0.299089,0.223811,0.123734,0.325602,0.291076,1.000000,0.274963
Cuisine,0.048805,0.048014,0.808274,0.563860,0.063178,0.720934,0.267418,0.274963,1.000000

In [164]:
data.corr()['target']

Longitude              0.071752
Latitude               0.070993
target                 1.000000
Has Table booking      0.642966
Has Online delivery    0.076953
Price range            0.847985
Aggregate rating       0.328440
Votes                  0.299089
Cuisine                0.808274
Name: target, dtype: float64

In [165]:
data.drop(columns=['Rating color','Has Online Delivery'],inplace=True)

KeyError: "['Has Online Delivery'] not found in axis"

In [150]:
#Encoding

In [151]:
X[:,0]=encoder.fit_transform(X[:,0])
X[:,-3]=encoder.fit_transform(X[:,-3])

NameError: name 'X' is not defined

In [103]:
X[0]

NameError: name 'X' is not defined

In [104]:
X.shape

NameError: name 'X' is not defined

In [105]:
from sklearn.preprocessing import OneHotEncoder
oencoder=OneHotEncoder(categorical_features=X[:,0])

NameError: name 'X' is not defined

In [152]:
X=X[:,1:]
X.shape

NameError: name 'X' is not defined

In [153]:
oencoder1=OneHotEncoder(categorical_features=[-3])
X=oencoder1.fit_transform(X).toarray()
X.shape

NameError: name 'X' is not defined

In [154]:
X=np.delete(X,-3,1)
X.shape

NameError: name 'X' is not defined

In [155]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

NameError: name 'X' is not defined

In [ ]:
X_train.shape

In [156]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression

In [157]:
regressor.fit(X_train,y_train)

NameError: name 'X_train' is not defined

In [158]:
y_pred=regressor.predict(X_test)
y_pred.shape

NameError: name 'X_test' is not defined

In [159]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

NameError: name 'y_test' is not defined

In [ ]:
X=oencoder.fit_transform(X).toarray()